In [32]:
##added dependencies

from keras.models import Sequential
from keras.layers import Dense
from keras.utils.np_utils import to_categorical
from keras.optimizers import SGD
import numpy as np
import pandas as pd
import sys

# Fix random seed for reproducibility
np.random.seed(7)

# 1. Load Iris species dataset
# Split into input (X) and output (Y) variables
Datacsv = pd.read_csv("Iris.csv")
print(Datacsv) # test purposes 


      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            

In [33]:
# Deletes first column with "Id"
Datacsv = Datacsv.drop("Id", 1)

In [34]:
# Convert Species to numeric id
Datacsv["Species"] = Datacsv["Species"].map({
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
}).astype(int)


In [35]:
# Converts data to a np matrix
dataset = Datacsv.as_matrix()
print(dataset)  #showing dataset matrix 

[[ 5.1  3.5  1.4  0.2  0. ]
 [ 4.9  3.   1.4  0.2  0. ]
 [ 4.7  3.2  1.3  0.2  0. ]
 [ 4.6  3.1  1.5  0.2  0. ]
 [ 5.   3.6  1.4  0.2  0. ]
 [ 5.4  3.9  1.7  0.4  0. ]
 [ 4.6  3.4  1.4  0.3  0. ]
 [ 5.   3.4  1.5  0.2  0. ]
 [ 4.4  2.9  1.4  0.2  0. ]
 [ 4.9  3.1  1.5  0.1  0. ]
 [ 5.4  3.7  1.5  0.2  0. ]
 [ 4.8  3.4  1.6  0.2  0. ]
 [ 4.8  3.   1.4  0.1  0. ]
 [ 4.3  3.   1.1  0.1  0. ]
 [ 5.8  4.   1.2  0.2  0. ]
 [ 5.7  4.4  1.5  0.4  0. ]
 [ 5.4  3.9  1.3  0.4  0. ]
 [ 5.1  3.5  1.4  0.3  0. ]
 [ 5.7  3.8  1.7  0.3  0. ]
 [ 5.1  3.8  1.5  0.3  0. ]
 [ 5.4  3.4  1.7  0.2  0. ]
 [ 5.1  3.7  1.5  0.4  0. ]
 [ 4.6  3.6  1.   0.2  0. ]
 [ 5.1  3.3  1.7  0.5  0. ]
 [ 4.8  3.4  1.9  0.2  0. ]
 [ 5.   3.   1.6  0.2  0. ]
 [ 5.   3.4  1.6  0.4  0. ]
 [ 5.2  3.5  1.5  0.2  0. ]
 [ 5.2  3.4  1.4  0.2  0. ]
 [ 4.7  3.2  1.6  0.2  0. ]
 [ 4.8  3.1  1.6  0.2  0. ]
 [ 5.4  3.4  1.5  0.4  0. ]
 [ 5.2  4.1  1.5  0.1  0. ]
 [ 5.5  4.2  1.4  0.2  0. ]
 [ 4.9  3.1  1.5  0.1  0. ]
 [ 5.   3.2  1.2  0.

In [36]:
#Cross Validation

trainingSet = np.random.randint(dataset.shape[0], size=100)
testSet = np.random.randint(dataset.shape[0], size=45)

xTrain = dataset[trainingSet, :4]
yTrain = to_categorical(dataset[trainingSet, 4], num_classes=3)

print("................XTrain...............")
print(xTrain)
print()


print("................YTrain...............")
print(yTrain)
print()

xTest = dataset[testSet, :4]
yTest = to_categorical(dataset[testSet, 4], num_classes=3)

print("................XTest................")
print(xTest)
print()

print("................YTest................")
print(yTest)
print()

................XTrain...............
[[ 5.   3.   1.6  0.2]
 [ 5.8  2.7  4.1  1. ]
 [ 6.3  2.9  5.6  1.8]
 [ 5.8  2.6  4.   1.2]
 [ 5.8  2.7  5.1  1.9]
 [ 5.1  3.3  1.7  0.5]
 [ 6.3  2.5  4.9  1.5]
 [ 5.5  2.5  4.   1.3]
 [ 6.5  3.2  5.1  2. ]
 [ 4.4  3.2  1.3  0.2]
 [ 6.3  3.4  5.6  2.4]
 [ 6.2  2.2  4.5  1.5]
 [ 6.1  3.   4.9  1.8]
 [ 7.7  3.   6.1  2.3]
 [ 5.1  3.5  1.4  0.2]
 [ 6.6  3.   4.4  1.4]
 [ 5.7  2.8  4.5  1.3]
 [ 4.6  3.4  1.4  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.1  3.8  1.9  0.4]
 [ 5.6  2.5  3.9  1.1]
 [ 6.3  3.3  4.7  1.6]
 [ 6.8  3.   5.5  2.1]
 [ 4.9  3.1  1.5  0.1]
 [ 6.3  3.3  4.7  1.6]
 [ 4.4  3.   1.3  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 6.4  3.1  5.5  1.8]
 [ 6.3  2.3  4.4  1.3]
 [ 6.3  2.5  4.9  1.5]
 [ 6.   2.7  5.1  1.6]
 [ 4.9  3.   1.4  0.2]
 [ 6.7  3.3  5.7  2.5]
 [ 7.7  2.6  6.9  2.3]
 [ 5.   2.3  3.3  1. ]
 [ 5.8  2.6  4.   1.2]
 [ 6.1  2.8  4.   1.3]
 [ 5.1  3.3  1.7  0.5]
 [ 5.4  3.7  1.5  0.2]
 [ 5.   3.2  1.2  0.2]
 [ 5.9  3.   4.2  1.5]
 [ 7.7  3.   6.1  2

In [37]:
# 4. Define Model

model = Sequential()  # Creating Sequential Model
model.add(Dense(32, input_dim=4, activation="relu"))
model.add(Dense(32, activation="relu"))
model.add(Dense(3, activation="sigmoid"))

In [38]:
# Compile the Model
# sgd = Stochastic gradient descent optimizer

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(
    loss='categorical_crossentropy',
    optimizer=sgd,
    metrics=['accuracy']
)

In [42]:
# Fit Model

model.fit(
    xTrain,
    yTrain,
    epochs=105,
    batch_size=10
)

Epoch 1/105
100/100 [==============================] - 0s 280us/step - loss: 0.0903 - acc: 0.9600
Epoch 2/105
100/100 [==============================] - 0s 200us/step - loss: 0.0952 - acc: 0.9500
Epoch 3/105
100/100 [==============================] - 0s 240us/step - loss: 0.0825 - acc: 0.9800
Epoch 4/105
100/100 [==============================] - 0s 280us/step - loss: 0.0882 - acc: 0.9700
Epoch 5/105
100/100 [==============================] - 0s 240us/step - loss: 0.0740 - acc: 0.9800
Epoch 6/105
100/100 [==============================] - 0s 280us/step - loss: 0.1233 - acc: 0.9600
Epoch 7/105
100/100 [==============================] - 0s 240us/step - loss: 0.1147 - acc: 0.9700
Epoch 8/105
100/100 [==============================] - 0s 240us/step - loss: 0.0747 - acc: 0.9800
Epoch 9/105
100/100 [==============================] - 0s 240us/step - loss: 0.0791 - acc: 0.9800
Epoch 10/105
100/100 [==============================] - 0s 250us/step - loss: 0.0916 - acc: 0.9700
Epoch 11/105
100/10

100/100 [==============================] - 0s 200us/step - loss: 0.0867 - acc: 0.9700
Epoch 84/105
100/100 [==============================] - 0s 200us/step - loss: 0.0721 - acc: 0.9800
Epoch 85/105
100/100 [==============================] - ETA: 0s - loss: 0.0844 - acc: 0.900 - 0s 240us/step - loss: 0.0798 - acc: 0.9700
Epoch 86/105
100/100 [==============================] - 0s 200us/step - loss: 0.0838 - acc: 0.9800
Epoch 87/105
100/100 [==============================] - 0s 320us/step - loss: 0.0812 - acc: 0.9700
Epoch 88/105
100/100 [==============================] - 0s 240us/step - loss: 0.0911 - acc: 0.9600
Epoch 89/105
100/100 [==============================] - 0s 200us/step - loss: 0.0836 - acc: 0.9700
Epoch 90/105
100/100 [==============================] - 0s 240us/step - loss: 0.0752 - acc: 0.9700
Epoch 91/105
100/100 [==============================] - 0s 200us/step - loss: 0.0708 - acc: 0.9800
Epoch 92/105
100/100 [==============================] - 0s 240us/step - loss: 0.0718

In [43]:
# Evaluate Model

scores = model.evaluate(xTest, yTest)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

45/45 [==============================] - 0s 89us/step

acc: 97.78%


In [44]:
# Save the predictions to a csv file named predictions.csv 

predictions = pd.DataFrame({
    "Ids": range(1, 151),
    "Species": [p.argmax() for p in model.predict(dataset[:, :4])]
})

predictions["Species"] = Datacsv["Species"].map({
    0: "Iris-setosa",
    1: "Iris-versicolor",
    2: "Iris-virginica"
}).astype(str)

predictions.to_csv("predictions.csv", index=False)
print("Saved To Predictions.csv")

Saved To Predictions.csv
